### ISSUE TITLE
DOMAnalyzer.attributesToStyles not handling width and height on img

### ISSUE THREAD

**Issue by Meisolsson** [radkovo/CSSBox#52]
`width` and `height` are not being read from the `img` tag.

**Comment by radkovo** [comment]
It's because their conversion to CSS is not straightforward; e.g. when the attributes are combined with an inline style definition containing percentages. Decoding of `width` and `height` is implemented separately in [CSSDecoder#computeReplacedObjectSize](https://github.com/radkovo/CSSBox/blob/master/src/main/java/org/fit/cssbox/layout/CSSDecoder.java#L130).
